### ISSUE TITLE
golang library ?

### ISSUE THREAD

**Issue by c-nv-s** [codomatech/clodss#4]
did you have plans to implement this as a golang library?

**Comment by mohamed--abdel-maksoud** [comment]
I don't see a use case. Redis is not much used in golang programs, and there is this amazing library for embedded storage (there is even a full redis server based on it):
https://github.com/dgraph-io/badger

What's your use case?

**Comment by c-nv-s** [comment]
ah sorry I misunderstood the purpose of this project from the context in which you linked to it from your comment on reddit. you can disregard this this ticket.
